# more info see https://docker.github.io/compose/compose-file/
version: '3.7'
networks:
  default:
    # Use a custom driver
    #driver: custom-driver-1
services:
  learn-python-evn:
    container_name: 'learn-python-evn'
    image: learn-python:1.0.0